### ISSUE TITLE
Filtering?

### ISSUE THREAD

**Issue by Duumke** [fnordpojk/merlin-dashboard#2]
Hi,

Thanks for developing such a nice dashboard.
Is there any way to exclude hosts and services from a certain group to be taken into account.
I would like to have an overview of all systems exept for a certain group (the group needs to be monitored, but actions to respond to issue's are for another person to fix, so I have no need to see them in my dashboard ;-)

I hope there's a way to get this done.

Thanks for your time.

Kind regards,
Duumke

**Comment by fnordpojk** [comment]
Hi,

As long as you're running the Livestatus version, it's exceedingly simple to add filtering:

https://github.com/fnordpojk/merlin-dashboard/blob/master/merlin2.php#L23-L25

Unfortunately for you, Matthias Kettner made a strange decision when he wrote Livestatus. There is only one operator that operates on lists (which group fields are), ">=", which means "contains". There is no "does not contain". Instead, he chooses to complicate things by adding the operator "Negate" to the And/Or operator group, which means that you would have to write your query like this:

Filter: groups >= thegroupidontwant
Negate:

..which just makes no sense whatsoever when he could have done:

Filter: groups !>= thegroupidontwant

Since the custom filter support in merlin-dashboard just inserts filters, it doesn't support the strange Negate syntax. You will have to hack the queries themselves in merlin2.php, adding the Filter and Negate after these lines:

https://github.com/fnordpojk/merlin-dashboard/blob/master/merlin2.php#L132
https://github.com/fnordpojk/merlin-dashboard/blob/master/merlin2.php#L192
https://github.com/fnordpojk/merlin-dashboard/blob/master/merlin2.php#L230
https://github.com/fnordpojk/merlin-dashboard/blob/master/merlin2.php#L337

Good luck!
